### ISSUE TITLE
OS X El Capitan > Run > Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by zolotykh** [malikshubham827/get-me-through#7]
```bash
stderr: Traceback (most recent call last):
  File "/Users/alexander/Documents/project/get-me-through/server/routes/../py/run.py", line 3, in <module>
    import cv2
  File "/usr/local/lib/python3.6/site-packages/cv2/__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/cv2/cv2.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /usr/local/lib/python3.6/site-packages/cv2/.dylibs/libavutil.55.78.100.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python3.6/site-packages/cv2/.dylibs/libavutil.55.78.100.dylib

 byyee
run.js -> success code:1 null
```

**Comment by malikshubham827** [comment]
Thanks @zolotykh for pointing out the issue.
The problem is that OpenCV3 a.k.a `cv2` needs libjpeg 8d version instead of 9b(latest at this time). With homebrew the version got upgraded to 9b and thus this incompatibility error.
You can switch to version 8d using
`$ brew switch libjpeg 8d
`
which I came to know from [here](https://github.com/homebrew/homebrew-php/issues/4358).

Please try it out and check if it works, it works for me though.
